#!/usr/bin/env python
# coding: utf-8

# In[5]:


import pandas as pd


# In[6]:


print(pd.__version__)


# ** creating series 

# In[7]:


arr= [0,1,2,3,4]
s1= pd.Series(arr)
s1


# In[8]:


order = [2,2,3,4,5]
s2 = pd.Series(arr, index=order)
s2


# In[9]:


import numpy as np
n= np.random.randn(5)
index=['a','b','c','d','e']
s2= pd.Series(n, index= index)
s2


# In[10]:


#create a series from dictionary
d={'a':3, 'b':2,'c':1, 'd':4, 'e':5}
s3= pd.Series(d)
s3


# In[11]:


# you can modify the index of the series
print(s1)


# In[12]:


s1.index = ['A','B','C','D','E']
s1


# In[13]:


#slicing
s1[2:]


# In[14]:


s4= s3.append(s1)
s4


# In[15]:


s4.drop('e')


# #series operation

# In[16]:


arr1= [0,1,2,3,4,5,7]
arr2= [6,7,8,9,5]


# In[17]:


s5= pd.Series(arr2)
s5


# In[18]:


s6= pd.Series(arr1)
s6


# In[19]:


s5.add(s6)


# In[20]:


s5.sub(s6)


# In[21]:


s5.mul(s6)


# In[22]:


print('median', s7.median())
print('max', s7.max())
print('min', s7.min())


# In[ ]:


s7=s5.div(s6)
s7


# # Create a dataframe

# In[23]:


dates= pd.date_range('today', periods=6)
num_arr=np.random.randn(6,4)
columns=['A','B','C','D']

df1= pd.DataFrame(num_arr, index= dates, columns=columns)
df1


# In[ ]:


dates


# In[24]:


data = {'animal':['cat','dog','cat','snake','dog','cow','tiger'],
         'age':[4,6,2,1.5,5,3,9],
         'visit':[1,4,5,np.nan,4,2,2],
         'priority':['yes','yes', 'no','no','yes','no','no'] }

labels =['a','b','c','d','e','f','g']

df2= pd.DataFrame(data,index=labels)
df2


# In[ ]:


df2.dtypes


# In[ ]:


df2.head()


# In[26]:


df2.describe() #to get statistical data 


# In[25]:


df2.T


# In[28]:


df2.sort_values(by='age')


# In[31]:


df2.sort_values(by='age')[1:3]


# In[34]:


df2[['age','visit']][1:3]


# In[35]:


df3= df2.copy()


# In[36]:


df3


# In[37]:


df3.isnull()


# In[38]:


df3.loc['f','age']= 4.0
df3


# In[41]:


df3.mean()


# In[44]:


df3['visit'].max()


# In[45]:


df3.sum()


# In[47]:


string= pd.Series(['A','B','C','Aaa', 'BaCa',np.nan,'CBA','cow','owl'])
string.str.lower()


# ## operation for dataframe missing Value 

# In[51]:


df4=df3.copy()
meanAge=df4['age'].mean()


# In[52]:


df4['age'].fillna(meanAge)


# In[53]:


df5=df3.copy()


# In[54]:


df5


# In[55]:


df5.dropna(how='any')


# In[56]:


df3.to_csv('animal.csv')


# In[58]:


df_animal=pd.read_csv('animal.csv')


# In[59]:


df_animal.head(3)


# In[64]:


df3.to_excel('animal.xlsx',sheet_name='Sheet1')
df_animal2= pd.read_excel('animal.xlsx','Sheet1',index_col=None, na_values=['NA'])
df_animal2


# #visualisationin pandas
# 

# In[3]:


import numpy as np
import matplotlib 
get_ipython().run_line_magic('matplotlib', 'inline')

ts= pd.Series(np.random.randn(50), index=pd.date_range('today', periods=50))
ts=ts.cumsum()
ts.plot


# In[ ]:





# In[ ]:




